name: arvin
description: آروین - مدیریت کارها، یادداشت‌ها و پیگیری‌ها
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  shamsi_date: ^1.1.1
  flutter_jalali_date_picker: ^2.2.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  share_plus: ^11.1.0
  pdf: ^3.12.0
  printing: ^5.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
