import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:shamsi_date/shamsi_date.dart';

String nid()=>DateTime.now().microsecondsSinceEpoch.toString();
String j(DateTime d){final x=Gregorian.fromDateTime(d).toJalali();return '${x.year}/${x.month.toString().padLeft(2,'0')}/${x.day.toString().padLeft(2,'0')}';}
String h(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';
bool day(DateTime a,DateTime b)=>a.year==b.year&&a.month==b.month&&a.day==b.day;
class F{String id,text;DateTime at;F({required this.id,required this.text,required this.at});Map<String,dynamic> toJson()=>{'id':id,'text':text,'at':at.toIso8601String()};factory F.fromJson(Map<String,dynamic>x)=>F(id:'${x['id']??nid()}',text:'${x['text']??''}',at:DateTime.tryParse('${x['at']}')??DateTime.now());}
class I{String id,title,note,cat;DateTime date;bool task,arc,trash;List<F> fs;I({required this.id,required this.title,required this.note,required this.cat,required this.date,required this.task,required this.fs,this.arc=false,this.trash=false});Map<String,dynamic>toJson()=>{'id':id,'title':title,'note':note,'cat':cat,'date':date.toIso8601String(),'task':task,'arc':arc,'trash':trash,'fs':fs.map((e)=>e.toJson()).toList()};factory I.fromJson(Map<String,dynamic>x)=>I(id:'${x['id']??nid()}',title:'${x['title']??''}',note:'${x['note']??''}',cat:'${x['cat']??'عمومی'}',date:DateTime.tryParse('${x['date']}')??DateTime.now(),task:x['task']==true,arc:x['arc']==true,trash:x['trash']==true,fs:(x['fs']??[]).map((e)=>F.fromJson(Map<String,dynamic>.from(e))).toList());}
void main()=>runApp(const A());
class A extends StatelessWidget{const A({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'آروین',theme:ThemeData(useMaterial3:true,fontFamily:'Vazirmatn'),home:const Directionality(textDirection:TextDirection.rtl,child:Home()));}
class Home extends StatefulWidget{const Home({super.key});@override State<Home>createState()=>_S();}
class _S extends State<Home>{List<I>items=[];List<String>cats=['عمومی'];String filter='همه';String cf='همه';bool load=true;@override void initState(){super.initState();read();}Future<void>read()async{final p=await SharedPreferences.getInstance();final r=p.getString('items');if(r!=null)items=(jsonDecode(r)as List).map((e)=>I.fromJson(Map<String,dynamic>.from(e))).toList();cats=p.getStringList('cats')??['عمومی'];if(!cats.contains('عمومی'))cats.insert(0,'عمومی');if(mounted)setState(()=>load=false);}Future<void>save()async{final p=await SharedPreferences.getInstance();await p.setString('items',jsonEncode(items.map((e)=>e.toJson()).toList()));await p.setStringList('cats',cats);}List<I>get list{final n=DateTime.now();return items.where((x)=>!x.trash).where((x){if(filter=='بایگانی')return x.arc;if(x.arc)return false;if(filter=='امروز')return day(x.date,n);if(filter=='آینده')return x.date.isAfter(n);if(filter=='عقب‌افتاده')return x.date.isBefore(n)&&!day(x.date,n);if(filter=='یادداشت‌ها')return !x.task;if(filter=='کارها')return x.task;return true;}).where((x)=>cf=='همه'||x.cat==cf).toList();}Future<void>edit([I? old])async{final r=await showModalBottomSheet<I>(context:context,isScrollControlled:true,builder:(_)=>Editor(old:old,cats:cats));if(r==null)return;if(old==null)items.add(r);else items[items.indexWhere((e)=>e.id==old.id)]=r;await save();setState((){});}Future<void>fu(I x,[F? old])async{final r=await showDialog<F>(context:context,builder:(_)=>FEd(old:old));if(r==null)return;if(old==null)x.fs.add(r);else x.fs[x.fs.indexOf(old)]=r;await save();setState((){});}
@override Widget build(BuildContext c){if(load)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(endDrawer:Drawer(child:ListView(padding:const EdgeInsets.only(top:40),children:[const ListTile(title:Text('آروین',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold))),...['همه','امروز','آینده','عقب‌افتاده','یادداشت‌ها','کارها','بایگانی'].map((v)=>ListTile(title:Text(v),onTap:(){setState(()=>filter=v);Navigator.pop(c);})),ListTile(title:const Text('دسته‌بندی‌ها'),onTap:()=>showDialog(context:c,builder:(_)=>CatDlg(values:cats,onSave:(v){cats=v.contains('عمومی')?v:['عمومی',...v];save();setState((){});}))) ])),appBar:AppBar(title:const Text('آروین'),actions:[Builder(builder:(b)=>IconButton(icon:const Icon(Icons.menu),onPressed:()=>Scaffold.of(b).openEndDrawer()))]),body:Column(children:[Padding(padding:const EdgeInsets.all(8),child:Row(children:[Expanded(child:DropdownButtonFormField<String>(initialValue:cf,items:['همه',...cats].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>cf=v??'همه'),decoration:const InputDecoration(labelText:'دسته‌بندی'))),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<String>(initialValue:filter,items:const['همه','امروز','آینده','عقب‌افتاده','یادداشت‌ها','کارها','بایگانی'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>filter=v??'همه'),decoration:const InputDecoration(labelText:'وضعیت')))])),Expanded(child:list.isEmpty?const Center(child:Text('موردی وجود ندارد')):ListView.builder(itemCount:list.length,itemBuilder:(_,i){final x=list[i];final last=x.fs.isEmpty?null:x.fs.last;return Dismissible(key:ValueKey(x.id),background:Container(alignment:Alignment.centerRight,padding:const EdgeInsets.all(20),child:const Text('بایگانی')),secondaryBackground:Container(alignment:Alignment.centerLeft,padding:const EdgeInsets.all(20),child:const Text('سطل زباله')),confirmDismiss:(d)async{if(d==DismissDirection.startToEnd)x.arc=true;else x.trash=true;await save();setState((){});return true;},child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>D(item:x,edit:()=>edit(x),fu:()=>fu(x)))),title:Text(x.title.isEmpty?'بدون عنوان':x.title),subtitle:Text('${x.cat} • ${j(x.date)} ${h(x.date)}\n${last==null?'بدون پیگیری':'آخرین پیگیری ${j(last.at)} ${h(last.at)}'}'),leading:Icon(x.task?Icons.task_alt:Icons.note_outlined)));}))]),floatingActionButton:FloatingActionButton(onPressed:()=>edit(),child:const Icon(Icons.add)));}}
class Editor extends StatefulWidget{final I?old;final List<String>cats;const Editor({super.key,this.old,required this.cats});@override State<Editor>createState()=>_E();}
class _E extends State<Editor>{late TextEditingController t,n;late String cat;late bool task;late DateTime date;@override void initState(){super.initState();final x=widget.old;t=TextEditingController(text:x?.title??'');n=TextEditingController(text:x?.note??'');cat=x?.cat??widget.cats.first;task=x?.task??false;date=x?.date??DateTime.now();}@override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.only(bottom:MediaQuery.of(c).viewInsets.bottom),child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:t,decoration:const InputDecoration(labelText:'عنوان')),TextField(controller:n,maxLines:6,decoration:const InputDecoration(labelText:'توضیحات / یادداشت')),SwitchListTile(title:const Text('فعال کردن پیگیری'),value:task,onChanged:(v)=>setState(()=>task=v)),DropdownButtonFormField<String>(initialValue:cat,items:widget.cats.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>cat=v??cat),decoration:const InputDecoration(labelText:'دسته‌بندی')),ListTile(title:Text('تاریخ: ${j(date)} ${h(date)}'),onTap:()async{final d=await showDatePicker(context:c,initialDate:date,firstDate:DateTime(2000),lastDate:DateTime(2100));if(d!=null)setState(()=>date=DateTime(d.year,d.month,d.day,date.hour,date.minute));}),FilledButton(onPressed:(){final title=t.text.trim().isEmpty?n.text.split('\n').first.trim():t.text.trim();Navigator.pop(c,I(id:widget.old?.id??nid(),title:title,note:n.text.trim(),cat:cat,date:date,task:task,fs:List<F>.from(widget.old?.fs??[]),arc:widget.old?.arc??false,trash:widget.old?.trash??false));},child:const Text('ذخیره'))])));}
class FEd extends StatefulWidget{final F?old;const FEd({super.key,this.old});@override State<FEd>createState()=>_FE();}class _FE extends State<FEd>{late TextEditingController t;late DateTime at;@override void initState(){super.initState();t=TextEditingController(text:widget.old?.text??'');at=widget.old?.at??DateTime.now();}@override Widget build(BuildContext c)=>AlertDialog(title:Text(widget.old==null?'پیگیری جدید':'ویرایش پیگیری'),content:TextField(controller:t,maxLines:4,decoration:const InputDecoration(labelText:'شرح پیگیری (اختیاری)')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('لغو')),FilledButton(onPressed:()=>Navigator.pop(c,F(id:widget.old?.id??nid(),text:t.text.trim(),at:at)),child:const Text('ذخیره'))]);}
class D extends StatelessWidget{final I item;final Future<void>Function()edit,fu;const D({super.key,required this.item,required this.edit,required this.fu});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(item.title),actions:[IconButton(onPressed:edit,icon:const Icon(Icons.edit))]),body:ListView(padding:const EdgeInsets.all(16),children:[Text(item.note.isEmpty?'بدون توضیحات':item.note,style:const TextStyle(fontSize:18)),Text('تاریخ: ${j(item.date)} ${h(item.date)}'),if(item.task)...[const Divider(),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('پیگیری‌ها',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),FilledButton(onPressed:fu,child:const Text('پیگیری جدید'))]),...item.fs.reversed.map((f)=>ListTile(title:Text(f.text.isEmpty?'(بدون شرح)':f.text),subtitle:Text('${j(f.at)} ${h(f.at)}')))]));}}
class CatDlg extends StatefulWidget{final List<String>values;final void Function(List<String>)onSave;const CatDlg({super.key,required this.values,required this.onSave});@override State<CatDlg>createState()=>_CD();}class _CD extends State<CatDlg>{late List<String>v;final c=TextEditingController();@override void initState(){super.initState();v=[...widget.values];}@override Widget build(BuildContext x)=>AlertDialog(title:const Text('دسته‌بندی‌ها'),content:SizedBox(width:320,height:300,child:Column(children:[TextField(controller:c,decoration:InputDecoration(labelText:'افزودن',suffixIcon:IconButton(icon:const Icon(Icons.add),onPressed:(){if(c.text.trim().isNotEmpty){setState(()=>v.add(c.text.trim()));c.clear();}}))),Expanded(child:ListView(children:v.map((e)=>ListTile(title:Text(e),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>setState(()=>v.remove(e))))).toList()))])),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('لغو')),FilledButton(onPressed:(){widget.onSave(v);Navigator.pop(x);},child:const Text('ذخیره'))]);}
