import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:shamsi_date/shamsi_date.dart';

void main()=>runApp(const ArvinApp());
String jdate(DateTime d){final j=Gregorian.fromDateTime(d).toJalali();return '${j.year}/${j.month}/${j.day}';}
String jtime(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';

class Follow{String text;DateTime at;Follow(this.text,this.at);Map<String,dynamic> toJson()=>{'text':text,'at':at.toIso8601String()};factory Follow.fromJson(Map<String,dynamic> x)=>Follow(x['text']??'',DateTime.parse(x['at']));}
class Entry{String title,description,category;DateTime date;bool task;List<String>tags;List<Follow>follows;Entry({required this.title,required this.description,required this.category,required this.date,required this.task,required this.tags,required this.follows});Map<String,dynamic>toJson()=>{'title':title,'description':description,'category':category,'date':date.toIso8601String(),'task':task,'tags':tags,'follows':follows.map((e)=>e.toJson()).toList()};factory Entry.fromJson(Map<String,dynamic>x)=>Entry(title:x['title'],description:x['description']??'',category:x['category']??'عمومی',date:DateTime.parse(x['date']),task:x['task']??false,tags:List<String>.from(x['tags']??[]),follows:(x['follows']as List).map((e)=>Follow.fromJson(Map<String,dynamic>.from(e))).toList());}

class ArvinApp extends StatefulWidget{const ArvinApp({super.key});@override State<ArvinApp>createState()=>_ArvinAppState();}
class _ArvinAppState extends State<ArvinApp>{bool dark=false;@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'آروین',theme:ThemeData(useMaterial3:true,fontFamily:'Vazirmatn',colorSchemeSeed:Colors.indigo),darkTheme:ThemeData(useMaterial3:true,fontFamily:'Vazirmatn',brightness:Brightness.dark,colorSchemeSeed:Colors.indigo),themeMode:dark?ThemeMode.dark:ThemeMode.light,home:Directionality(textDirection:TextDirection.rtl,child:Home(toggle:()=>setState(()=>dark=!dark))));}

class Home extends StatefulWidget{final VoidCallback toggle;const Home({super.key,required this.toggle});@override State<Home>createState()=>_HomeState();}
class _HomeState extends State<Home>{List<Entry>items=[];List<String>cats=['عمومی'];String filter='همه',sort='آخرین وارده';bool reverse=false;
@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();final s=p.getString('arvin');if(s!=null)items=(jsonDecode(s)as List).map((e)=>Entry.fromJson(Map<String,dynamic>.from(e))).toList();cats=p.getStringList('cats')??['عمومی'];setState((){});}Future<void>save()async{final p=await SharedPreferences.getInstance();await p.setString('arvin',jsonEncode(items.map((e)=>e.toJson()).toList()));await p.setStringList('cats',cats);}
bool today(DateTime d){final n=DateTime.now();return d.year==n.year&&d.month==n.month&&d.day==n.day;}List<Entry>get shown{var x=items.where((e){if(filter=='یادداشت‌ها')return !e.task;if(filter=='کارها')return e.task;if(filter=='امروز')return today(e.date);if(filter=='آینده')return e.date.isAfter(DateTime.now());if(filter=='عقب‌افتاده')return e.date.isBefore(DateTime.now())&&!today(e.date);return true;}).toList();x.sort((a,b){final z=sort=='عنوان'?a.title.compareTo(b.title):sort=='تاریخ'?a.date.compareTo(b.date):a.follows.length.compareTo(b.follows.length);return reverse?z:-z;});return x;}
void edit({Entry? old,bool task=true}){final t=TextEditingController(text:old?.title??''),d=TextEditingController(text:old?.description??''),g=TextEditingController(text:old?.tags.join(', ')??'');String cat=old?.category??cats.first;DateTime date=old?.date??DateTime.now();showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>StatefulBuilder(builder:(c,set){return Padding(padding:EdgeInsets.only(bottom:MediaQuery.of(c).viewInsets.bottom),child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(children:[TextField(controller:t,decoration:const InputDecoration(labelText:'عنوان *')),TextField(controller:d,maxLines:3,decoration:const InputDecoration(labelText:'توضیحات')),DropdownButtonFormField<String>(value:cat,items:cats.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>set(()=>cat=v??cat),decoration:const InputDecoration(labelText:'دسته‌بندی')),TextField(controller:g,decoration:const InputDecoration(labelText:'تگ‌ها')),ListTile(title:Text('تاریخ شمسی: ${jdate(date)}'),onTap:()async{final v=await showDatePicker(context:c,firstDate:DateTime(2020),lastDate:DateTime(2100),initialDate:date);if(v!=null)set(()=>date=DateTime(v.year,v.month,v.day,date.hour,date.minute));}),ListTile(title:Text('ساعت: ${jtime(date)}'),onTap:()async{final v=await showTimePicker(context:c,initialTime:TimeOfDay.fromDateTime(date));if(v!=null)set(()=>date=DateTime(date.year,date.month,date.day,v.hour,v.minute));}),FilledButton(onPressed:(){if(t.text.trim().isEmpty)return;setState((){if(old==null)items.add(Entry(title:t.text.trim(),description:d.text.trim(),category:cat,date:date,task:task,tags:g.text.split(',').map((e)=>e.trim()).where((e)=>e.isNotEmpty).toList(),follows:[]));else{old.title=t.text.trim();old.description=d.text.trim();old.category=cat;old.date=date;old.tags=g.text.split(',').map((e)=>e.trim()).where((e)=>e.isNotEmpty).toList();}});save();Navigator.pop(c);},child:const Text('ذخیره'))]));}));}
void details(Entry e){Navigator.push(context,MaterialPageRoute(builder:(_)=>Details(e:e,onEdit:()=>edit(old:e,task:e.task),onChange:(){setState((){});save();})));}
void follow(Entry e){final c=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('ثبت پیگیری'),content:TextField(controller:c,maxLines:4,decoration:const InputDecoration(labelText:'شرح پیگیری')),actions:[TextButton(onPressed:(){if(c.text.trim().isNotEmpty){setState(()=>e.follows.add(Follow(c.text.trim(),DateTime.now())));save();}Navigator.pop(context);},child:const Text('ثبت'))]));}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('آروین • $filter'),actions:[IconButton(icon:const Icon(Icons.sort),onPressed:()=>showModalBottomSheet(context:c,builder:(_)=>Column(mainAxisSize:MainAxisSize.min,children:['آخرین وارده','تاریخ','عنوان'].map((s)=>ListTile(title:Text(s),onTap:(){setState((){if(sort==s)reverse=!reverse;else{sort=s;reverse=false;}});Navigator.pop(c);})).toList()))),IconButton(icon:const Icon(Icons.menu),onPressed:()=>showModalBottomSheet(context:c,builder:(_)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[for(final f in ['امروز','آینده','عقب‌افتاده','یادداشت‌ها','کارها'])ListTile(title:Text(f),onTap:(){setState(()=>filter=f);Navigator.pop(c);}),ListTile(title:const Text('حالت تاریک/روشن'),onTap:(){Navigator.pop(c);widget.toggle();})]))))]),body:shown.isEmpty?const Center(child:Text('هنوز موردی ثبت نشده است')):ListView.builder(itemCount:shown.length,itemBuilder:(_,i){final e=shown[i];return Card(child:ListTile(onTap:()=>details(e),leading:Icon(e.task?Icons.task_alt:Icons.note),title:Text(e.title),subtitle:Text('${e.category} • ${e.follows.isEmpty?'بدون پیگیری':'آخرین پیگیری '+jtime(e.follows.last.at)}\n${jdate(e.date)} • ${jtime(e.date)}'),trailing:e.task?IconButton(icon:const Icon(Icons.add_task),onPressed:()=>follow(e)):null));}),floatingActionButton:FloatingActionButton(onPressed:()=>showModalBottomSheet(context:c,builder:(_)=>Wrap(children:[ListTile(title:const Text('یادداشت جدید'),onTap:(){Navigator.pop(c);edit(task:false);}),ListTile(title:const Text('کار جدید'),onTap:(){Navigator.pop(c);edit();})])),child:const Icon(Icons.add)));
}

class Details extends StatelessWidget{final Entry e;final VoidCallback onEdit,onChange;const Details({super.key,required this.e,required this.onEdit,required this.onChange});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(e.title),actions:[IconButton(icon:const Icon(Icons.edit),onPressed:onEdit)]),body:ListView(padding:const EdgeInsets.all(16),children:[Text(e.description.isEmpty?'بدون توضیحات':e.description,style:const TextStyle(fontSize:18)),const SizedBox(height:15),Text('تاریخ: ${jdate(e.date)} • ${jtime(e.date)}'),Text('دسته: ${e.category}'),if(e.tags.isNotEmpty)Wrap(children:e.tags.map((x)=>Chip(label:Text(x))).toList()),if(e.task)...[const Divider(),const Text('سوابق پیگیری',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...e.follows.reversed.map((f)=>ListTile(title:Text(f.text),subtitle:Text('${jdate(f.at)} • ${jtime(f.at)}')))]]);}}
