import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:shamsi_date/shamsi_date.dart';

String makeId() => DateTime.now().microsecondsSinceEpoch.toString();
String jd(DateTime d) { final j = Gregorian.fromDateTime(d).toJalali(); return '${j.year}/${j.month.toString().padLeft(2,'0')}/${j.day.toString().padLeft(2,'0')}'; }
bool sameDay(DateTime a, DateTime b) => a.year==b.year && a.month==b.month && a.day==b.day;

class FollowUp {
  String id,text; DateTime at;
  FollowUp({required this.id,required this.text,required this.at});
  Map<String,dynamic> toJson()=>{'id':id,'text':text,'at':at.toIso8601String()};
  factory FollowUp.fromJson(Map<String,dynamic> x)=>FollowUp(id:'${x['id'] ?? makeId()}',text:'${x['text'] ?? ''}',at:DateTime.tryParse('${x['at']}') ?? DateTime.now());
}
class Item {
  String id,title,note,category; DateTime date; bool task,archived,trash; List<FollowUp> followUps;
  Item({required this.id,required this.title,required this.note,required this.category,required this.date,required this.task,required this.followUps,this.archived=false,this.trash=false});
  Map<String,dynamic> toJson()=>{'id':id,'title':title,'note':note,'category':category,'date':date.toIso8601String(),'task':task,'archived':archived,'trash':trash,'followUps':followUps.map((e)=>e.toJson()).toList()};
  factory Item.fromJson(Map<String,dynamic> x)=>Item(id:'${x['id'] ?? makeId()}',title:'${x['title'] ?? ''}',note:'${x['note'] ?? x['description'] ?? ''}',category:'${x['category'] ?? x['cat'] ?? 'عمومی'}',date:DateTime.tryParse('${x['date']}') ?? DateTime.now(),task:x['task']==true,archived:x['archived']==true || x['arc']==true,trash:x['trash']==true || x['trashed']==true,followUps:(x['followUps'] ?? x['fs'] ?? []).map((e)=>FollowUp.fromJson(Map<String,dynamic>.from(e))).toList());
}
Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); runApp(const Arvin()); }
class Arvin extends StatelessWidget { const Arvin({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'آروین',theme:ThemeData(useMaterial3:true,fontFamily:'Vazirmatn'),home:const Directionality(textDirection:TextDirection.rtl,child:Home())); }
class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  List<Item> items=[]; List<String> cats=['عمومی']; String filter='همه',catFilter='همه'; bool loading=true;
  @override void initState(){super.initState();load();}
  Future<void> load() async { final p=await SharedPreferences.getInstance(); final raw=p.getString('arvin_items') ?? p.getString('items'); if(raw!=null&&raw.isNotEmpty) items=(jsonDecode(raw) as List).map((e)=>Item.fromJson(Map<String,dynamic>.from(e))).toList(); cats=p.getStringList('arvin_categories') ?? p.getStringList('cats') ?? ['عمومی']; if(!cats.contains('عمومی'))cats.insert(0,'عمومی'); if(mounted)setState(()=>loading=false); }
  Future<void> save() async { final p=await SharedPreferences.getInstance(); await p.setString('arvin_items',jsonEncode(items.map((e)=>e.toJson()).toList())); await p.setStringList('arvin_categories',cats); }
  List<Item> get shown { final now=DateTime.now(); final r=items.where((x)=>!x.trash).where((x){ if(catFilter!='همه'&&x.category!=catFilter)return false; if(filter=='بایگانی')return x.archived; if(x.archived)return false; if(filter=='امروز')return sameDay(x.date,now); if(filter=='آینده')return x.date.isAfter(now); if(filter=='عقب‌افتاده')return x.date.isBefore(now)&&!sameDay(x.date,now); if(filter=='یادداشت‌ها')return !x.task; if(filter=='کارها')return x.task; return true; }).toList(); r.sort((a,b)=>b.date.compareTo(a.date)); return r; }
  Future<void> editItem([Item? old]) async { final r=await showModalBottomSheet<Item>(context:context,isScrollControlled:true,builder:(_)=>Editor(old:old,cats:cats)); if(r==null)return; if(old==null)items.add(r); else { final i=items.indexWhere((e)=>e.id==old.id); if(i>=0)items[i]=r; } await save(); if(mounted)setState((){}); }
  Future<void> follow(Item item,[FollowUp? old]) async { final r=await showDialog<FollowUp>(context:context,builder:(_)=>FollowDialog(old:old)); if(r==null)return; if(old==null)item.followUps.add(r); else { final i=item.followUps.indexOf(old); if(i>=0)item.followUps[i]=r; } await save(); if(mounted)setState((){}); }
  Future<void> categoriesDialog() async { final v=await showDialog<List<String>>(context:context,builder:(_)=>CategoryDialog(values:cats)); if(v!=null){cats=v.contains('عمومی')?v:['عمومی',...v]; await save(); if(mounted)setState((){});} }
  Future<void> trashDialog() async { await showDialog<void>(context:context,builder:(dialogContext){ final list=items.where((e)=>e.trash).toList(); return AlertDialog(title:const Text('سطل زباله'),content:list.isEmpty?const Text('خالی است'):SizedBox(width:320,height:300,child:ListView(children:list.map((x)=>ListTile(title:Text(x.title.isEmpty?'بدون عنوان':x.title),trailing:IconButton(icon:const Icon(Icons.restore),onPressed:()async{x.trash=false;await save();if(mounted)setState((){});if(dialogContext.mounted)Navigator.pop(dialogContext);}))).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext),child:const Text('بستن'))]); }); }
  @override Widget build(BuildContext c){ if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator())); final shownItems=shown; return Scaffold(endDrawer:Drawer(child:SafeArea(child:ListView(children:[const DrawerHeader(child:Text('آروین',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold))),...['همه','امروز','آینده','عقب‌افتاده','یادداشت‌ها','کارها','بایگانی'].map((v)=>ListTile(title:Text(v),onTap:(){setState(()=>filter=v);Navigator.pop(c);})),ListTile(title:const Text('دسته‌بندی‌ها'),onTap:(){Navigator.pop(c);categoriesDialog();}),ListTile(title:const Text('سطل زباله'),onTap:(){Navigator.pop(c);trashDialog();})]))),appBar:AppBar(title:const Text('آروین'),actions:[Builder(builder:(b)=>IconButton(icon:const Icon(Icons.menu),onPressed:()=>Scaffold.of(b).openEndDrawer()))]),body:Column(children:[Padding(padding:const EdgeInsets.all(8),child:Row(children:[Expanded(child:DropdownButtonFormField<String>(initialValue:catFilter,items:['همه',...cats].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>catFilter=v??'همه'),decoration:const InputDecoration(labelText:'دسته‌بندی'))),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<String>(initialValue:filter,items:const['همه','امروز','آینده','عقب‌افتاده','یادداشت‌ها','کارها','بایگانی'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>filter=v??'همه'),decoration:const InputDecoration(labelText:'وضعیت')))])),Expanded(child:shownItems.isEmpty?const Center(child:Text('موردی وجود ندارد')):ListView.builder(itemCount:shownItems.length,itemBuilder:(_,i){final x=shownItems[i];final last=x.followUps.isEmpty?null:x.followUps.last;return Dismissible(key:ValueKey(x.id),background:Container(alignment:Alignment.centerRight,padding:const EdgeInsets.all(20),child:const Text('بایگانی')),secondaryBackground:Container(alignment:Alignment.centerLeft,padding:const EdgeInsets.all(20),child:const Text('سطل زباله')),confirmDismiss:(d)async{if(d==DismissDirection.startToEnd)x.archived=true;else x.trash=true;await save();if(mounted)setState((){});return true;},child:ListTile(title:Text(x.title.isEmpty?'بدون عنوان':x.title),subtitle:Text('${x.category} • ${jd(x.date)}\n${last==null?'بدون پیگیری':'آخرین پیگیری: ${jd(last.at)}'}'),leading:Icon(x.task?Icons.task_alt:Icons.note_outlined),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Details(item:x,onEdit:()=>editItem(x),onFollow:()=>follow(x),onSave:save)))));}))),floatingActionButton:FloatingActionButton(onPressed:()=>editItem(),child:const Icon(Icons.add))); }
}
class Editor extends StatefulWidget { final Item? old; final List<String> cats; const Editor({super.key,this.old,required this.cats}); @override State<Editor> createState()=>_EditorState(); }
class _EditorState extends State<Editor>{ late TextEditingController title,note; late String cat; late bool task; late DateTime date; @override void initState(){super.initState();final x=widget.old;title=TextEditingController(text:x?.title??'');note=TextEditingController(text:x?.note??'');cat=x?.category??widget.cats.first;task=x?.task??false;date=x?.date??DateTime.now();}
  Future<void>pick()async{final d=await showDatePicker(context:context,firstDate:DateTime(2000),lastDate:DateTime(2100),initialDate:date);if(d!=null)setState(()=>date=DateTime(d.year,d.month,d.day,date.hour,date.minute));}
  void submit(){String t=title.text.trim();if(t.isEmpty)t=note.text.split('\n').map((e)=>e.trim()).firstWhere((e)=>e.isNotEmpty,orElse:()=> '');final out=Item(id:widget.old?.id??makeId(),title:t,note:note.text.trim(),category:cat,date:date,task:task,followUps:List<FollowUp>.from(widget.old?.followUps??const []),archived:widget.old?.archived??false,trash:widget.old?.trash??false);Navigator.pop(context,out);}
  @override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.only(bottom:MediaQuery.viewInsetsOf(c).bottom),child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:title,decoration:const InputDecoration(labelText:'عنوان')),TextField(controller:note,maxLines:6,decoration:const InputDecoration(labelText:'توضیحات / یادداشت')),SwitchListTile(title:const Text('این مورد یک کار است'),value:task,onChanged:(v)=>setState(()=>task=v)),DropdownButtonFormField<String>(initialValue:cat,items:widget.cats.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>cat=v??cat),decoration:const InputDecoration(labelText:'دسته‌بندی')),ListTile(title:Text('تاریخ: ${jd(date)}'),subtitle:const Text('تاریخ گذشته هم قابل انتخاب است'),onTap:pick),FilledButton(onPressed:submit,child:const Text('ذخیره'))]))); }
class FollowDialog extends StatefulWidget{final FollowUp?old;const FollowDialog({super.key,this.old});@override State<FollowDialog>createState()=>_FollowDialogState();}
class _FollowDialogState extends State<FollowDialog>{late TextEditingController text;late DateTime at;@override void initState(){super.initState();text=TextEditingController(text:widget.old?.text??'');at=widget.old?.at??DateTime.now();}void submit()=>Navigator.pop(context,FollowUp(id:widget.old?.id??makeId(),text:text.text.trim(),at:at));@override Widget build(BuildContext c)=>AlertDialog(title:Text(widget.old==null?'ثبت پیگیری':'ویرایش پیگیری'),content:TextField(controller:text,maxLines:4,decoration:const InputDecoration(labelText:'شرح پیگیری (اختیاری)')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('لغو')),FilledButton(onPressed:submit,child:const Text('ذخیره'))]);}
class Details extends StatelessWidget{final Item item;final Future<void>Function()onEdit,onFollow,onSave;const Details({super.key,required this.item,required this.onEdit,required this.onFollow,required this.onSave});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(item.title.isEmpty?'بدون عنوان':item.title),actions:[IconButton(onPressed:onEdit,icon:const Icon(Icons.edit))]),body:ListView(padding:const EdgeInsets.all(16),children:[Text(item.note.isEmpty?'بدون توضیحات':item.note,style:const TextStyle(fontSize:18)),const SizedBox(height:12),Text('تاریخ: ${jd(item.date)}'),Text('دسته: ${item.category}'),const Divider(height:32),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('پیگیری‌ها',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),FilledButton(onPressed:onFollow,child:const Text('پیگیری جدید'))]),...item.followUps.reversed.map((f)=>ListTile(title:Text(f.text.isEmpty?'(بدون شرح)':f.text),subtitle:Text(jd(f.at))))]));}
class CategoryDialog extends StatefulWidget{final List<String>values;const CategoryDialog({super.key,required this.values});@override State<CategoryDialog>createState()=>_CategoryDialogState();}
class _CategoryDialogState extends State<CategoryDialog>{late List<String>v;final c=TextEditingController();@override void initState(){super.initState();v=[...widget.values];}@override Widget build(BuildContext x)=>AlertDialog(title:const Text('دسته‌بندی‌ها'),content:SizedBox(width:320,height:300,child:Column(children:[TextField(controller:c,decoration:InputDecoration(labelText:'دسته جدید',suffixIcon:IconButton(icon:const Icon(Icons.add),onPressed:(){final s=c.text.trim();if(s.isNotEmpty&&!v.contains(s)){setState(()=>v.add(s));c.clear();}}))),Expanded(child:ListView(children:v.map((e)=>ListTile(title:Text(e),trailing:e=='عمومی'?null:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>setState(()=>v.remove(e))))).toList()))])),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('لغو')),FilledButton(onPressed:()=>Navigator.pop(x,v),child:const Text('ذخیره'))]);}
